# To run the Alpine Tomcat image on a container
# docker run --name boi_web_server -d -p 8080:8080 --link boi_db_server:boi_db_server cigital/boi_web_server

FROM jeanblanchard/tomcat:8

RUN echo 'Setting up the Apache Tomcat server ...'

ADD BankOfInsecurities.war /opt/tomcat/webapps/

RUN echo 'Apache Server set up is complete ...'

