
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: Ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Perform Quick Static Analysis Download SIGMA from Artifactory
    - name: Quick Static Analysis with SIGMA2
      run: |
        wget --user josew --password ${{ secrets.ARTIFACTORY_PASSWORD}} http://salesaf.blackduck.synopsys.com/artifactory/detect-local/sigma
        chmod +x sigma
        ./sigma -V
        ./sigma analyze  --format github ./
        
    # Upload SIGMA findings
    - name: Upload SIGMA results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: sigma-results.json

    # Perform Software Composition Analysis2
    - name: Software Composition Analysis  Rapid Scan with Black Duck
      uses: blackducksoftware/github-action@v2
      with:
        version: 7
        args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --blackduck.trust.cert="true" --detect.blackduck.scan.mode=RAPID'
